### ISSUE TITLE
Do not know how to solve this....

### ISSUE THREAD

**Issue by haousa** [thomas694/iPhoneMediaTransfer#6]
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'iTunesMobileDevice.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MK.MobileDevice.Lite.MobileDevice.AMDeviceNotificationSubscribe(ITMDDeviceNotificationCallback callback, UInt32 unused1, UInt32 unused2, UInt32 unused3, Void*& am_device_notification_ptr)
   at MK.MobileDevice.Lite.iOSDeviceMK.doConstruction()
   at iPhoneMediaTransfer.Program.Main(String[] args)

**Comment by thomas694** [comment]
You need the drivers as specified in [How to download these packages?](https://github.com/thomas694/iPhoneMediaTransfer?tab=readme-ov-file#how-to-download-these-packages) of the Readme.

**Comment by iyevhen** [comment]
installed iTunes 2.1.1 and it doesn't work. "c:\Program Files (x86)\Common Files\Apple\*"  is missing iTunesMobileDevice.dll

**Comment by thomas694** [comment]
You've a typo in the version number.
I'm pretty sure the information provided is correct. Please check what you downloaded and where it's installed. Then you'll find the files and it will work.
